### ISSUE TITLE
'QdrantClient' object has no attribute 'check_collection'

### ISSUE THREAD

**Issue by jayjk13** [qdrant/landing_page#1027]
`check_collection` attribute is not present.

**Comment by timvisee** [comment]
What programming language are you using? And on what page do you see this suggested?

**Comment by jayjk13** [comment]
Using python, official [documentation](https://arc.net/l/quote/uyervbsv) of the attribute.

**Comment by timvisee** [comment]
Does this work:

```python
client.collection_exists(collection_name="{collection_name}")
```

Because that's what I [see](https://qdrant.tech/documentation/concepts/collections/#check-collection-existence):

![image](https://github.com/user-attachments/assets/1a577bd2-2148-4489-a6c9-1c6e59fe1290)

**Comment by jayjk13** [comment]
Fixed the issue, was using an older qdrant version. @timvisee thanks.
