### ISSUE TITLE
Wrong units in multiple articles

### ISSUE THREAD

**Issue by morsik** [qdrant/landing_page#1048]
Some articles contains technical information with wrong units. In [some](https://qdrant.tech/articles/dedicated-service/) [places](https://qdrant.tech/articles/scalar-quantization/) there are `Gb` units (Gigabits) instead of clearly something that should be as `GB` (Gigabytes).

Images in first link also clearly shows wrong units.

**Comment by kacperlukawski** [comment]
Thank you, @morsik. The PR is ready and will hopefully be merged soon.
