### ISSUE TITLE
Add GDPR seal to out homepage

### ISSUE THREAD

**Issue by sgalonska** [qdrant/landing_page#1054]
We are working with heydata.eu to maintain GDPR compliance. They have therefore provided us with a 'seal' that we can embed on our website in order to ilustrate our GDPR compliance.
This is the embed code:

`<a href="https://heydata.eu" target="_blank" title="heyData GDPR seal"><img alt="heyData trusted logo" src="https://privacy-seal.heydata.eu/seal/73b958ae-33aa-49a9-abef-b703939f14ff?lang=en&design=design2&sealType=GDPR" style="border: 0" width="600" height="600" /></a>`

Please embed the seal where you see fit.

**Comment by davidmyriel** [comment]
@Anush008 Do you think we should put this in the footer next to the other badge?
<img width="1072" alt="Screenshot 2024-09-24 at 9 36 20 PM" src="https://github.com/user-attachments/assets/e6535b40-a644-4ee4-8b37-56a93b104129">

**Comment by Anush008** [comment]
Next to the SOC badge? +1.
