### ISSUE TITLE
Cloud Agent not working v1.30.3

### ISSUE THREAD

**Issue by dev-ago** [qdrant/landing_page#1128]
We are installing the Qdrant Agent on Kubernetes 1.30.3 but when we start the container we get the following error:

```
panic: neither $XDG_CONFIG_HOME nor $HOME are defined

goroutine 1 [running]:
github.com/notaryproject/notation-go/dir.loadUserPath()
    /go/pkg/mod/github.com/notaryproject/notation-go@v1.1.0/dir/path.go:85 +0xc5
github.com/notaryproject/notation-go/dir.init.0()
    /go/pkg/mod/github.com/notaryproject/notation-go@v1.1.0/dir/path.go:77 +0xf
Stream closed EOF for qdrant/qdrant-cloud-agent-fb86cb499-72q9k (qdrant-cloud-agent)
```

The strangest thing of all is that the same installation with the same values in a cluster practically the same, only with version 1.27.10 works without any problem.

Should we take into consideration some configuration in the podSecurityContext or securityContext in the Helm Chart values?

We can't explain the error, since the cluster configuration is the same.

**Comment by Anush008** [comment]
If the issue persists, please reach out to the team on our Discord server.
https://discord.gg/qdrant
