### ISSUE TITLE
Can you also add relevant functions to perform sparse embedding inference

### ISSUE THREAD

**Issue by microcoder-py** [qdrant/landing_page#1223]
Method to generate sparse embeds with FastEmbed was provided, inference options without Vector DB was not

**Comment by Anush008** [comment]
Does https://github.com/qdrant/fastembed?tab=readme-ov-file#-sparse-text-embeddings help?

**Comment by microcoder-py** [comment]
Hi @Anush008 thanks, I had managed to find them last month itself. Thanks for replying. I was hoping to use it with Chroma, but as it turns out it doesn't support Sparse Embeds either way. I have switched to QDrant
