### ISSUE TITLE
Example is incomplete, obsolete

### ISSUE THREAD

**Issue by markwkiehl** [qdrant/landing_page#1262]
https://qdrant.tech/documentation/embeddings/ollama/

Here is a better example:

from qdrant_client import QdrantClient
from qdrant_client.models import Batch, Distance, VectorParams, models

# pip install ollama
import ollama

# Create the text corpus
docs = ["Qdrant is a vector similarity search engine.",
        "Qdrant can save a vector store in memory, locally to disk, and in the cloud.",
        "Ollama is an open-source platform that allows users to run large language models (LLMs) on their local computer.",
        "Ollama excels in niche applications with specific embeddings.",
        ]

# Generate the embeddings from the docs, ids, and payloads.
ids = []
embeddings = []
payloads = []
for i,doc in enumerate(docs):
    ids.append(i)
    payloads.append({"doc": doc})
    embedding = ollama.embeddings(model="mxbai-embed-large", prompt=doc)["embedding"]
    embeddings.append(embedding)

# Initialize Qdrant client
qdrant_client = QdrantClient(":memory:")

# Create a Qdrant collection

# Define a collection name
collection_name = "NicheApplications"

# Calculate the dimension of the embedding
vector_size = len(embeddings[0])

qdrant_client.create_collection(
    collection_name=collection_name,
    vectors_config=VectorParams(size=vector_size, 
                                distance=Distance.COSINE,
                                datatype=models.Datatype.FLOAT16,   # FLOAT16 uses half memory of FLOAT32 while having virtually no impact on the quality of vector search.
                                ),       
)

# Upsert the embedding into Qdrant
qdrant_client.upsert(
    collection_name=collection_name,
    points=Batch(
        ids=ids,
        vectors=embeddings,
        payloads = payloads,
    )
)

# Do a vector search on the Qdrant vector store

query = "Is Ollama open source?"

# Create embedding from the query
embedding_query = ollama.embeddings(model="mxbai-embed-large", prompt=query)["embedding"]

# Search the vector store and return the five closest points (limit=5) for the embedding query.
hits = qdrant_client.search(
    collection_name=collection_name,
    query_vector=embedding_query,
    limit=5     
)
hit = hits[0]
print("Best match from vector store to the query '" + query + "' is id=" + str(hit.id) + " with score=" + str(hit.score) + " and payload:" + str(hit.payload))
# Best match from vector store to the query 'Is Ollama open source?' is id=2 with score=0.7990983286492732 and payload:{'doc': 'Ollama is an open-source platform that allows users to run large language models (LLMs) on their local computer.'}

**Comment by generall** [comment]
Hey @markwkiehl, could you please make it a PR?
