### ISSUE TITLE
nfs storage

### ISSUE THREAD

**Issue by nkarthik** [qdrant/landing_page#1296]
Hello, 

I can deploy the qdrant in distributed mode with NFS persistent storage in 3 pods, each with its own storage space from NFS. Using vectordbbench to test the feasibility and it's completed the test for Search performance test 1Million with 768 Dim. 

I also tested collection creation with HNSW indexing and memmap_thresold like below, insert, and ran a search query. they are working. 

client.create_collection(
    collection_name="test_collection",
    #vectors_config=models.VectorParams(size=768, distance=models.Distance.COSINE),
    vectors_config=models.VectorParams(size=4, distance=models.Distance.DOT),
    optimizers_config=models.OptimizersConfigDiff(memmap_threshold=20000),
    hnsw_config=models.HnswConfigDiff(on_disk=True),
)

The qdrant installation section (https://qdrant.tech/documentation/guides/installation/#storage) mentioned that "Qdrant won’t work with [Network file systems](https://en.wikipedia.org/wiki/File_system#Network_file_systems) such as NFS, or Object storage systems such as S3."

can you please elaborate and provide more details such as which operations are not supported as well as supported operations with NFS or object storage?   

Regards, 
Karthikeyan Nagalingam

**Comment by generall** [comment]
any operations are not guaranteed with NFS

**Comment by generall** [comment]
We don't have tests for NFS, and our internals assume the guarantees provided by the posix file system. It might look like it works with NFS if you try, but we provide absolutely no guarantees if it is going to be stable.

**Comment by generall** [comment]
there are no single "memmap" in qdrant, but you can change storage path here https://github.com/qdrant/qdrant/blob/master/config/config.yaml#L14

**Comment by timvisee** [comment]
> 1. when we enable on-disk=true, does qdrant write all the data to the "/qdrant/storage" folder?

Yes. All data is written there even if not providing the flag. But if you do set `on_disk=true` it's likely that it'll put the data there and memory map it.

> 2. can I have multiple storagepath like one for each collection?

No. Is there a specific reason on why you might want this?

> I would like to see the data writes go to the /netapp folder, but data resides in /qdrant/storage. Can you please guide me ?

I don't understand what you mean by this. `memmap:path:/netapp` is not an option we provide.

The paths you can change are `storage.storage_path`, `storage.snapshots_path` and `storage.temp_path`.

Note that if you'd like to change configuration parameters, it's probably easier to change `config.yaml` directly.

**Comment by timvisee** [comment]
> Regarding multiple storagepath, based on performance requirements, we can create a collection on different types of storage devices underneath.

I see. While not the same, if using memory mapping the kernel will already take care of keeping hot data in memory. What I mean is that with memory mapping, hot collections are automatically kept in cache.

Also, you can deploy collection specific parameters such as whether data is kept in memory or not.

If you really want different types of disks you may want to run multiple instances.

> Regarding the Answer to question 3, I am running qdrant in a Kubernetes cluster. I can update the config.yaml via configMap. Is there any other way to change the config.yaml directly?

If you're doing it that way, that's already totally fine. I made the assumption you were just testing locally. So you can keep `config.yaml` as is.
