### ISSUE TITLE
Improve Code Snippet Language Selection in Documentation

### ISSUE THREAD

**Issue by mmabrouk** [qdrant/landing_page#1328]
In the current documentation, each code snippet features tabs for selecting different programming languages. However, currently, users must manually select their language for each individual snippet. 

**Proposed Enhancement:**
It would enhance user experience significantly if the tabs were interconnected. For instance, when a user selects Python in one snippet, all code snippets should automatically switch to Python. 

![CleanShot 2024-11-29 at 12 21 56@2x](https://github.com/user-attachments/assets/0e7a31bb-1b60-4a82-a4b7-3fe5f53eb63e)

**Comment by Anush008** [comment]
Hey @mmabrouk. This was also raised in #899 and #132
We decided not to go ahead with this due to https://github.com/qdrant/landing_page/pull/900#issuecomment-2117475531.

**Comment by mmabrouk** [comment]
Thanks for the answer @Anush008 
Looking forward to the new theme!

**Comment by Anush008** [comment]
The new theme is live at https://qdrant.tech/

The old one was https://deploy-preview-900--condescending-goldwasser-91acf0.netlify.app/.

**Comment by mmabrouk** [comment]
hmmm.. I am a bit confused.

In #900 you say that you will implement this in the new theme. And it seems that you have already migrated to the new theme, yet closed all the issues about this.

Maybe I am missing something.

**Comment by Anush008** [comment]
This feature will not be implemented. Due to
> Now if language changes on a snippet in the middle or the end of the page it makes the whole page jump.

as mentioned in https://github.com/qdrant/landing_page/pull/900#issuecomment-2117475531

**Comment by Anush008** [comment]
Resolved with https://github.com/qdrant/landing_page/pull/2291
