### ISSUE TITLE
better side-panel on the documentation page

### ISSUE THREAD

**Issue by generall** [qdrant/landing_page#141]
- Move table on content for the single page (links to headers) on the right side
- Introduce categories - pages should be grouped into categories as it currently works for the table of contents. 
  - If no category for the page is specified, it stays as is.
  - We should indicate if the item is a category or a direct page with some icon (foldable or not)
- Introduce category names, which should separate pages

Implement all as a separate PRs

**Comment by davidmyriel** [comment]
Here is a sample breakdown for documentation:


Getting Started (category, grouped in its own directory)
	Quick Start (markdown file in that directory)
	Qdrant 101
	API Specification (custom link to an outside address)
	Client Libraries

Qdrant Manual
	Collections
	Payload
	Points
	Search
	etc……….

Tutorials
	tutorial 1
	tutorial 2
	tutorial 3
	tutorial 4

Integrations
	LangChain
	LlamaIndex
	DocArray
	Haystack
	etc…….

Release Notes (individual md file)
Technical Support (individual md file)
