### ISSUE TITLE
404 message for Edit on GitHub link 

### ISSUE THREAD

**Issue by davidmyriel** [qdrant/landing_page#150]
Edit on GitHub link at the bottom of the webpage needs the path variable updated. 
We just created new folders and the link to repo doesnt work for docs inside of folders....only for docs on the first level of the directory.

Try to edit http://qdrant.tech/documentation/concepts/collections/ 
It doesn't lead to the right folder in the repo.

**Comment by generall** [comment]
fixed in https://github.com/qdrant/landing_page/commit/82367b199179be1cb93362973af1e8256f3e9e9b
