### ISSUE TITLE
Copying text comes with extra line

### ISSUE THREAD

**Issue by coszio** [qdrant/landing_page#219]
When using the clipboard button on code snippets, it gets copied with an extra newline, which makes it a little awkward, specially for terminal commands

### Example

<img width="984" alt="image" src="https://github.com/qdrant/landing_page/assets/62079184/74793341-3182-49f2-87e3-11c5612878c0">

copies to:

```
docker pull qdrant/qdrant

```

instead of just:

```
docker pull qdrant/qdrant
```

### Reproducibility

Happens with every code block

**Comment by davidmyriel** [comment]
@coszio should be good now - can you check?

**Comment by coszio** [comment]
@davidmyriel Just checked, issue is still present. Not sure if it makes a difference but my platform is macOS
