### ISSUE TITLE
Document upgrade procedure

### ISSUE THREAD

**Issue by agourlay** [qdrant/landing_page#258]
Users are often asking how to upgrade an existing qdrant deployment to a new version.

It does not seem documented anywhere.

The official answer is to upgrade the minor versions sequentially.

**Comment by davidmyriel** [comment]
Thanks for letting me know. I will make a doc.

**Comment by generall** [comment]
https://qdrant.tech/documentation/faq/qdrant-fundamentals/#how-do-i-avoid-issues-when-updating-to-the-latest-version
