### ISSUE TITLE
Duplicate CSS rules in `css/custom-animate.css`

### ISSUE THREAD

**Issue by hugo-sid** [qdrant/landing_page#269]
## What's the issue?

Duplicate CSS rules in:
https://github.com/qdrant/landing_page/blob/765cb2962c8e6f240a0c56a6de4b6c23e92fd399/qdrant-landing/themes/qdrant/static/css/custom-animate.css#L262-L280

## What's the fix?
Looking at the other keyframes rules, I feel that adding the `-webkit-` prefix could be the fix.

## Good news

Based on preliminary inspection, I see that `qdrant-landing/themes/qdrant/static/css/custom-animate.css` is not being used on the website. So, the website is not impacted by this bug.

**Comment by Mstanic05** [comment]
Can you assign this to me!

**Comment by Anush008** [comment]
Closing since this no longer applicable on the new site.
