### ISSUE TITLE
Duplicate CSS rules in `css/blocks/_forms.scss`

### ISSUE THREAD

**Issue by hugo-sid** [qdrant/landing_page#270]
## What's the issue

There are multiple issues in file `css/blocks/_forms.scss`.

## Issue 1: duplicate `font-weight` CSS rule at 2 places:

https://github.com/qdrant/landing_page/blob/765cb2962c8e6f240a0c56a6de4b6c23e92fd399/qdrant-landing/themes/qdrant/static/css/blocks/_forms.scss#L187-L207

https://github.com/qdrant/landing_page/blob/765cb2962c8e6f240a0c56a6de4b6c23e92fd399/qdrant-landing/themes/qdrant/static/css/blocks/_forms.scss#L284-L299

### What's the fix?

Maintainers can decide which rule to use.

## Issue 2: duplicate selector `.styled-form .form-group .radio-box label` and styles

https://github.com/qdrant/landing_page/blob/765cb2962c8e6f240a0c56a6de4b6c23e92fd399/qdrant-landing/themes/qdrant/static/css/blocks/_forms.scss#L134-L158

## Issue 3: duplicate selector `.styled-form .form-group .check-box label` and styles

https://github.com/qdrant/landing_page/blob/765cb2962c8e6f240a0c56a6de4b6c23e92fd399/qdrant-landing/themes/qdrant/static/css/blocks/_forms.scss#L231-L255

### What's the fix?
Remove duplicate `color: var(--brand-secondary)` rule. Consolidate CSS rules. I have opened a PR to fix this.

**Comment by Anush008** [comment]
Closing since this is no longer applicable on the new site.
