### ISSUE TITLE
Duplicate CSS rules in `css/_reset.scss`

### ISSUE THREAD

**Issue by hugo-sid** [qdrant/landing_page#271]
## What's the issue?

Duplicate CSS rules for the `img` tag.
https://github.com/qdrant/landing_page/blob/765cb2962c8e6f240a0c56a6de4b6c23e92fd399/qdrant-landing/themes/qdrant/static/css/_reset.scss#L128-L141

## What's the fix?

Remove the duplicate rules.

**Comment by Anush008** [comment]
Closing since this is no longer applicable on the new site.
