### ISSUE TITLE
Improve mobile view padding and font size

### ISSUE THREAD

**Issue by RamchandraWarang9822** [qdrant/landing_page#294]
- [ ] Landing container padding
- [ ] Details card seperation ( adding border and box shadow can work)
- [ ] Making a single design for buttons and button-containers and using it throughout the page for uniformity
- [ ] Margin for company logos in [here](https://github.com/qdrant/landing_page/blob/ab32d9113467ebdea6a25db8b1a5bf8f8f408c9e/qdrant-landing/themes/qdrant/layouts/index.html#L204)

- We can add padding left and right to the container in mobile view and also improve the font size 
![image](https://github.com/qdrant/landing_page/assets/92023869/437cdfcf-adb2-4a80-926e-2565622183c7)

- Seperate these cards to look good
![image](https://github.com/qdrant/landing_page/assets/92023869/d412a935-b04c-4180-85ad-9915c5b164c1)
 
 - Make buttons uniform 
![image](https://github.com/qdrant/landing_page/assets/92023869/31ad78ae-5716-42cf-95be-d72707ee8dfc)
![image](https://github.com/qdrant/landing_page/assets/92023869/26429f05-4812-42b4-a34e-7b5f7b049d1b)

- Padding to icons and border radius to scroll up button
![image](https://github.com/qdrant/landing_page/assets/92023869/4c8899a4-0459-4092-a104-05e3ba1204a2)

**Comment by kkapil94** [comment]
Can I work on this issue?

**Comment by Anush008** [comment]
With the new site, this issue is no longer applicable.
