### ISSUE TITLE
Update Lookup in groups documentation

### ISSUE THREAD

**Issue by joein** [qdrant/landing_page#307]
We have an issue in python-client repository: https://github.com/qdrant/qdrant-client/issues/296

I believe it might be caused by the lack of some details in "Lookup in groups" documentation

1) The sentence about how the matching is done when we use `with_lookup` is not noticeable, I think it should be moved closer to the image with collections.
2) `lookup_from` behaviour is missing. It should be described because it might be complicated to understand it without just trying out experiments. (We take vector ids from `positives` and `negatives`, extract vectors from lookup collection by these ids, construct our "search_vector" and search with it in the "main" collection)

It might also be useful to mention that this lookup collection can be treated as pure payload collection, i.e. it is not necessary to store some meaningful vectors in it, however vector configuration should be set during collection creation and field with something during upload (e.g. `None` or `[0]`)

**Comment by davidmyriel** [comment]
Will reach out asap with a draft.

**Comment by joein** [comment]
In recommend and recommend groups we have an argument lookup_from

It has a brief description in the api reference
https://qdrant.github.io/qdrant/redoc/index.html#tag/points/operation/recommend_points:~:text=lookup_from-,LookupLocation%20(object)%20or%20(any%20or%20null),collection%20should%20have%20the%20same%20vector%20size%20as%20the%20current%20collection,-Responses

it is not mentioned in Recommendation API nor it is mentioned in Recommend groups

I thought about a scheme demonstrating that we fetch vectors from another collection by a point id but maybe we even don't need it and a simple description is enough
