### ISSUE TITLE
Cleaner section links

### ISSUE THREAD

**Issue by coszio** [qdrant/landing_page#330]
## Current Behavior
When browsing the documentation, we often want to share the links to specific sections, for example:
```
https://qdrant.tech/documentation/concepts/collections/#collections
```

However, if we first use the search bar to look for stuff, a query param `selector` is added to the URL, and any further sections that we select will also have the big selector string
```
https://qdrant.tech/documentation/concepts/collections/?selector=aHRtbCA%2BIGJvZHkgPiBkaXY6bnRoLW9mLXR5cGUoMSkgPiBzZWN0aW9uID4gZGl2ID4gZGl2ID4gZGl2ID4gYXJ0aWNsZSA%2BIGgx#collections
```

It would make our life easier if we could just copy the URL without cleaning it afterwards for sharing it. Note that including the selector does not make the link unusable, but it makes the URL harder to read when pasted in chats.

## Expected behavior
Links from the search bar should omit the `selector` query param 

Another solution would be that clicking on the link icon of each title should remove the `selector` query param.

**Comment by generall** [comment]
https://github.com/qdrant/landing_page/pull/358
