### ISSUE TITLE
Docker Run Command is not working in document

### ISSUE THREAD

**Issue by ashishpatel26** [qdrant/landing_page#426]
```bash
docker run -p 6333:6333 -p 6334:6334 \
    -v $(pwd)/qdrant_storage:/qdrant/storage:z \
    qdrant/qdrant
```

When I tried to execute this it is throwing error like this:
```bash
docker: Error response from daemon: create $(pwd)qdrantstorage: "$(pwd)qdrantstorage" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

Reference : https://qdrant.tech/documentation/quick-start/

**Comment by timvisee** [comment]
The above snippet assumes that you're running in a bash shell. Then, `$(pwd)` is replaced with your current working directory.

Is it possible that you're using some other shell where `$(pwd)` doesn't work? Or are you running the command through something else, and not in a bash shell directly?

**Comment by mjang** [comment]
Hi @ashishpatel26 , I've heard of this kind of error for Windows users. Here's a related [Reddit discussion](https://www.reddit.com/r/docker/comments/kxrf71/pwd_includes_invalid_characters_for_a_local/?onetap_auto=true)

If the suggestions there don't work, you could try to include the absolute path, based on a directory where you have full permissions. For example, if you're running bash in Linux (or using the Windows Subsystem for Linux), and your home directory is `/home/name` you could try:

```
docker run -p 6333:6333 -p 6334:6334 \
    -v /home/name/qdrant_storage:/qdrant/storage:z \
    qdrant/qdrant
```
