### ISSUE TITLE
Update year to 2024 in footer

### ISSUE THREAD

**Issue by hugo-sid** [qdrant/landing_page#491]
## What's the issue?

It's 2024 🎉, but the Qdrant website hasn't been updated yet; it still displays 2023 in the footer.

![image](https://github.com/qdrant/landing_page/assets/122173059/bda4b362-eacd-47ce-954b-69e1a6655a22)

## Fix

I believe, triggering a new deploy on Netlify will fix this issue; unless Netlify CI runners are in a location where it's still 2023. 😃 

## Reference(s)

https://github.com/qdrant/landing_page/blob/4e9b0d95553613d09598331786ab70441a806a98/qdrant-landing/themes/qdrant/layouts/partials/footer.html#L95-L98

**Comment by timvisee** [comment]
This has now been resolved with recent updates. Happy 2024! :smile:
