### ISSUE TITLE
docs: a small typo on capacity-sizing

### ISSUE THREAD

**Issue by Samra10** [qdrant/landing_page#591]
fix a small typo on _capacity-sizing.md_
https://github.com/qdrant/landing_page/blob/257818b206bf31d0863083a2582727ca5102066d/qdrant-landing/content/documentation/cloud/capacity-sizing.md#L46

`senatio` should be `scenario`

**Comment by timvisee** [comment]
Thank you! I've opened <https://github.com/qdrant/landing_page/pull/592> to patch this.
