### ISSUE TITLE
Service internal error: Failed to flush id_tracker mapping: Service runtime error: RocksDB flush_cf error: IO error: Stale file handle

### ISSUE THREAD

**Issue by cumtcstian** [qdrant/landing_page#621]
when i get the collection info , with GET collections/{my_collection}, 
the reponse : `{
  "result": {
    "status": "red",
    "optimizer_status": {
      "error": "Service internal error: Failed to flush id_tracker mapping: Service runtime error: RocksDB flush_cf error: IO error: Stale file handle"
    },
    "vectors_count": 79,
.....
`
get the points of this collection  is normal ,but i get this error when delete、create or update any point in this collection

**Comment by timvisee** [comment]
I've not seen this before.

Could you try to restart your Qdrant instance and see if the issue persists?

Also, could you check if you're seeing any errors for:
- reaching the file handle limit
- being out of disk space
