### ISSUE TITLE
Scrolling Issues in Qdrant docs

### ISSUE THREAD

**Issue by EteimZ** [qdrant/landing_page#642]
While using the live version of the Qdrant docs I noticed I can't scroll within the sidebar. I tried it in two browsers firefox and chrome.

**Comment by mjang** [comment]
Hi @EteimZ , 

I see scrollbars when I navigate to https://qdrant.tech/documentation/ in both Firefox and Chrome. Maybe you accidentally disabled them?

**Comment by mjang** [comment]
Thank you for explaining, @EteimZ . I can still scroll on both browsers, even though I don't see the intermediate scroll bars. You're welcome to propose a solution by PR.
