### ISSUE TITLE
Blog/article snippets font is different and less pleasant than that of the docs

### ISSUE THREAD

**Issue by KShivendu** [qdrant/landing_page#660]
## [Docs snippets](https://qdrant.tech/blog/binary-quantization-mistral-embed/):
![docs-snippet](https://github.com/qdrant/landing_page/assets/47217984/f65f20a4-ac85-4e83-bbaa-c49e3e004afb)

# [Blog snippets](https://qdrant.tech/documentation/quick-start/):
![code-snippet-blog](https://github.com/qdrant/landing_page/assets/47217984/202f9fad-f468-4d84-ba92-8a4812e4edcb)

The docs snippets font is different and I feel the same should be used in the blog.

**Comment by trean** [comment]
We have implemented the new design and now use similar code snippets font in our blog, articles, and documentation pages. Therefore, closing this issue as completed.
