### ISSUE TITLE
Qdrant-Spark Write Fails

### ISSUE THREAD

**Issue by pradeepdataml** [qdrant/landing_page#734]
Hi All.

I'm trying to write a spark-frame into qdrant. Below is the error I'm facing:
![image](https://github.com/qdrant/landing_page/assets/158282464/849a8287-a44e-4d42-b5dc-34292f23e1f9)

Also adding code the snippet I'm using:
![image](https://github.com/qdrant/landing_page/assets/158282464/0d8af67b-133d-4f56-84fa-8f551b3bf4ef)
![image](https://github.com/qdrant/landing_page/assets/158282464/9a1a6606-a4ac-4e1a-8ab8-035ce8dbf628)

Be great if someone could help with the same.

**Comment by Anush008** [comment]
Hi @pradeepdataml. The Spark connector uses Qdrant's GRPC interface. By default it should be at port `6334`.

**Comment by Anush008** [comment]
Hi @pradeepdataml. The Spark connector uses Qdrant's GRPC interface. By default, it should be at port `6334`.
