### ISSUE TITLE
Would like an example on not using Aleph Alpha

### ISSUE THREAD

**Issue by alucard001** [qdrant/landing_page#776]
Hi

I am trying to build a image search project using Qdrant, and come across this tutorial page.

https://qdrant.tech/documentation/tutorials/aleph-alpha-search/#multimodal-semantic-search-with-aleph-alpha

While this page is using Aleph Alpha API to do embedding, what if I don't want to use it?  I just want to not use any 3rd parties service other than Qdrant.  

Are there any precompiled model that I can use within Qdrant to do embedding?  Any example on that?

Thank you very much.

**Comment by Anush008** [comment]
No. Qdrant server doesn't have an embedding model of its own.
You can give https://github.com/qdrant/fastembed a try. Image embeddings are supported.

**Comment by alucard001** [comment]
> No. Qdrant server doesn't have an embedding model of its own. You can give https://github.com/qdrant/fastembed a try. Image embeddings are supported.

Very nice.  I'll give it a try.  Thank you.
