### ISSUE TITLE
Why does the one-hot algorithm store 1, but the query comes out with 0.4472136

### ISSUE THREAD

**Issue by sidikaisi** [qdrant/landing_page#919]
My program calculated the vector values of 0 and 1 through the one-hot algorithm and stored them in the vector database, but the result of the query vector was 0.4472136

**Comment by timvisee** [comment]
Are you using the Cosine distance metric by any chance?

When using Cosine, the vectors you upload are normalized. Normalization is likely the cause of seeing a value like this. Other distance metrics don't use normalization.
